langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key:
      model-name: Qwen/Qwen2.5-72B-Instruct
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key:
      model-name: Qwen/Qwen2.5-72B-Instruct
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://api.siliconflow.cn/v1
      api-key:
      model-name: netease-youdao/bce-embedding-base_v1
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10

  chroma:
    base-url: http://localhost:8000
    collection-name: interview-knowledge

  redis:
      host: localhost
      port: 6379
      password:
          enabled: false
      timeout: 5000

logging:
  level:
    dev.langchain4j: debug

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interviewer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234




mybatis:
  configuration:
    map-underscore-to-camel-case: true



